---
- name: install redis
  hosts: kochava
  vars:
    redis_port: 6378
    redis_password: authentication
    redis_stop_writes_on_bgsave_error: "no"
  roles:
    - DavidWittman.redis
- name: install php, php-redis
  hosts: kochava
  vars_files:
    - php_config.yml
  roles:
    - geerlingguy.php-redis
- name: install apache
  hosts: kochava
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
- name: install golang
  hosts: kochava
  roles:
    - role: gantsign.golang
      golang_gopath: '$HOME/workspace-go'
- hosts: kochava
  tasks:
    - name: copy file to kochava
      sudo: yes
      copy:
        src: ingest.php
        dest: /var/www/html
        owner: justin
        group: sudo
        mode: 0644